apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: application-ingress-rules
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - hosts: connected-city.com
    http:
      paths:
      - backend:
          serviceName: connectedcity-service
          servicePort: 80
  - hosts: connected-factory.com
    http:
      paths:
      - backend:
          serviceName: connectedfactory-service
          servicePort: 80 