apiVersion: v2
name: demo-chart-01
appVersion: "1.0"
description: a demo helm chart for connect application
version: 1.0.0
type: application
dependencies:
- name: traefik
  version: 10.6.0
  repository: https://helm.traefik.io/traefik 